import type {Metadata} from 'next';
import {Noto_Sans} from 'next/font/google';
import './globals.css';
import styles from './layout.module.css';
import {ReactNode} from 'react';
import Header from '@/layout/Header/Header';
import Sidebar from '@/layout/Sidebar/Sidebar';
import Footer from '@/layout/Footer/Footer';
import cn from 'classnames';

const inter = Noto_Sans({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
    children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(inter.className, styles.container)}>
				<Header className={styles.header}/>
				<Sidebar className={styles.sidebar}/>
				<div className={styles.body}>
					{children}
				</div>
				<Footer className={styles.footer}/>
			</body>
		</html>
	);
}
